server:
  forward-headers-strategy: native
  port: 8080
  error:
    include-message: always

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false
